apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lkpm1fx2i-python
  janus-idp.io/tekton: lkpm1fx2i-python
  backstage.io/kubernetes-id: lkpm1fx2i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lkpm1fx2i-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
